name: PR Closed

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
    - name: Print github.ref_name
      run: |
          echo ${{ github.ref_name }}

    - name: Print github.ref
      run: |
          echo ${{ github.ref }}
