name: Delete

on:
  delete:

  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
    - name: Print github.ref_name
      run: |
          echo ${{ github.ref_name }}

    - name: Print github.ref
      run: |
          echo ${{ github.ref }}

    - name: Print github.event.ref
      run: |
          echo ${{ github.event.ref }}
