name: Push and PR

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print github.ref_name
      run: |
          echo ${{ github.ref_name }}

    - name: Print github.ref
      run: |
          echo ${{ github.ref }}
